# Generated by Django 4.2.4 on 2023-12-31 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
