# Generated by Django 4.2.4 on 2024-01-01 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('secimg', models.ImageField(blank=True, null=True, upload_to='sectionimages/')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='headimg',
            field=models.ImageField(null=True, upload_to='blogimages/'),
        ),
        migrations.DeleteModel(
            name='APIKey',
        ),
        migrations.AddField(
            model_name='section',
            name='blogpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpost.post'),
        ),
    ]
