# Generated by Django 4.2.4 on 2024-01-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0011_profile_delete_customuser_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='profile',
        ),
    ]
