# Generated by Django 4.2.4 on 2024-01-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0012_rename_author_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.TextField(default="it's a wonderful day"),
            preserve_default=False,
        ),
    ]
