# Generated by Django 4.2.4 on 2024-01-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0013_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commentcount',
            field=models.IntegerField(default=0),
        ),
    ]
