# Generated by Django 4.2.4 on 2024-01-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0014_post_commentcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='displaypic',
            field=models.ImageField(null=True, upload_to='profileimages/'),
        ),
    ]
