# Generated by Django 4.2.4 on 2024-01-03 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0015_profile_displaypic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='dateposted created'),
            preserve_default=False,
        ),
    ]
