# Generated by Django 4.2.4 on 2024-01-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0016_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replycount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='totalcount',
            field=models.IntegerField(default=0),
        ),
    ]
