# Generated by Django 4.2.4 on 2024-01-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0017_comment_replycount_post_totalcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
