# Generated by Django 4.2.4 on 2024-01-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0022_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
