# Generated by Django 4.2.4 on 2024-01-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0023_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(default='marksyapoe@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='email',
            field=models.CharField(default='marksyapoe@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
