# Generated by Django 4.2.4 on 2024-01-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0024_comment_email_reply_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='email',
        ),
    ]
