# Generated by Django 4.2.4 on 2024-01-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0025_remove_reply_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
    ]
