# Generated by Django 4.2.4 on 2024-01-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0026_post_ispublished'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
