# Generated by Django 4.2.4 on 2024-01-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0027_profile_is_editor_profile_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='draft_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='published_post',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='totalpost_impressions',
            field=models.IntegerField(default=0),
        ),
    ]
